export const GET_PHONES_REQUEST = 'GET_PHONES_REQUEST';
export const GET_PHONES_SUCCESS = 'GET_PHONES_SUCCESS';
export const GET_PHONES_ERROR = 'GET_PHONES_ERROR';
export const GET_PHONE = 'GET_PHONE';